# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft Versioning
minecraft_version=1.16.5
minecraft_release_version=1.16.5
minecraft_version_range=[1.16,1.16.5]

# Mod Properties
mod_version=1.0.0
maven_group=com.draconicvelum
archives_base_name=HotbarAutoFill

# Forge Properties
forge_version=36.2.42

# Fabric Properties
yarn_mappings=1.16.5+build.10
loader_version=0.14.25
loader_version_range=>=0.14.0
fabric_minecraft_version_range=>=1.16 <=1.16.5
