# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft Versioning
minecraft_version=1.10.2
minecraft_release_version=1.10.2
minecraft_version_range=[1.10,1.10.2]

# Mod Properties
mod_version=1.0.0
maven_group=com.draconicvelum
archives_base_name=HotbarAutoFill

# Forge Properties
forge_version=12.18.3.2511
minecraft_version_json_url=https://piston-meta.mojang.com/v1/packages/3d47b3d4d4a29efce4f2f978720a9644224a9ce8/1.10.2.json
