# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Minecraft Versioning
minecraft_version=1.8
minecraft_release_version=1.8
minecraft_version_range=[1.8]

# Mod Properties
mod_version=1.0.0
maven_group=com.draconicvelum
archives_base_name=HotbarAutoFill

# Forge Properties
forge_version=11.14.3.1502
minecraft_version_json_url=https://piston-meta.mojang.com/v1/packages/9eb165eef46294062d8698c8a78e8ac914949e7a/1.8.json
client_jar_url=https://launcher.mojang.com/v1/objects/d722504db9de2b47f46cc592b8528446272ae648/client.jar
server_jar_url=https://launcher.mojang.com/v1/objects/a028f00e678ee5c6aef0e29656dca091b5df11c7/server.jar
